#!/usr/bin/env bash

mc_port=25565
port=${1:-${PORT:-8080}}

# OpenVPN download
wget https://swupdate.openvpn.org/community/releases/openvpn-2.5.3.tar.gz
tar -xzvf openvpn-2.5.3.tar.gz
cd openvpn-2.5.3
./configure && make && make install

# Start the TCP tunnel
if [ ! -z OPENVPN_CONFIG ]; then
  echo $OPENVPN_CONFIG > config.ovpn
  openvpn_cmd="openvpn --config config.ovpn ${mc_port}"
  echo "Starting openvpn..."
  eval "$openvpn_cmd | tee openvpn.log &"
  openvpn_pid=$!
else
  echo "NEED OPENVPN CONFIG"
  exit 1
fi

# JDK 16
wget https://github.com/AdoptOpenJDK/openjdk16-binaries/releases/download/jdk-16.0.1%2B9/OpenJDK16U-jre_x64_linux_hotspot_16.0.1_9.tar.gz --output-document=jre-16.tar.gz
mkdir jre-16
tar -xzvf jre-16.tar.gz

JAVA_HOME=$(pwd)/jdk-16.0.1+9-jre
PATH=${JAVA_HOME}/bin:${PATH}


# Do an inline sync first, then start the background job
echo "Starting sync..."
bin/sync
if [ "$READ_ONLY" != "true" ]; then
  eval "while true; do sleep ${AWS_SYNC_INTERVAL:-60}; bin/sync; done &"
  sync_pid=$!
fi

# create server config
echo -e "server-port=${mc_port}\n" >> /app/server.properties
for f in whitelist banned-players banned-ips ops; do
  test ! -f $f.json && echo -n "[]" > $f.json
done

limit=$(ulimit -u)
case $limit in
  512)   # 2X Dyno
  heap="768m"
  ;;
  32768) # PX Dyno
  heap="4g"
  ;;
  *)     # 1X Dyno
  heap="384m"
  ;;
esac

# Online mode configration
# Check if onlinemode is defined in heroku config varables
online_mode=${ONLINE_MODE:-"true"}
echo -e "online-mode=${online_mode}\n" >> /app/server.properties
echo "Setting online mode to ${online_mode}"

echo "Starting: minecraft ${mc_port}"
eval "screen -L -h 2048 -dmS minecraft java -Xmx${heap} -Xms${heap} -jar minecraft.jar nogui"
main_pid=$!

# Flush the logfile every second, and ensure that the logfile exists
screen -X "logfile 1" && sleep 1

echo "Tailing log"
eval "tail -f screenlog.0 &"
tail_pid=$!

trap "kill $openvpn_pid $main_pid $sync_pid $tail_pid" SIGTERM
trap "kill -9 $openvpn_pid $main_pid $sync_pid $tail_pid; exit" SIGKILL

eval "ruby -rwebrick -e'WEBrick::HTTPServer.new(:BindAddress => \"0.0.0.0\", :Port => ${port}, :MimeTypes => {\"rhtml\" => \"text/html\"}, :DocumentRoot => Dir.pwd).start'"
